### ISSUE TITLE
Актуальность задачи распознавания captcha

### ISSUE THREAD

**Issue by sdukshis** [foma99999/diplom#12]
Написать 500 слов об актуальности задачи по распознаванию captcha

**Comment by foma99999** [comment]
Получилось 343 слова. Можно растянуть текст на 500 конечно, но общий смысл останется такой же.


<hr>

На сегодняшний момент задача распознавания каптчи является актуальной, поскольку решив ее, можно произвести аудит безопасности алгоритма генерации каптчи. 

Зачем это нужно? Все популярные сервисы, которыми пользуются миллионы людей, используют в качестве защиты от автоматизации действий каптчу. Распознавая графическую защиту мы может автоматизировать любое действие на данном сервисе: будь то рассылка спама, засорение базы данных миллионами «мусорных» регистрации или забивание тикет-системы техподдержки этими же миллионами «мусорных» запросов, тем самым, нанося убыток сервису и делая его менее комфортным для простых пользователей.

Проведя аудит, мы может сказать насколько сервис уязвим подобному способу атаки и при необходимости рассказать как можно максимально обезопасить сервис, делая каптчу максимально непригодной для автоматизированного распознавания, но возможной для распознавания человеком.

По состоянию на 2013 год, каждый день пользователями по всей планете вводится примерно 320 миллионов каптчей. 

Если приложить задачу немного в другое русло, то алгоритмы для распознавания каптчи можно использовать в качестве основы атакующего комплекса, что позволит сохранить огромные средства людям, занимающимся атаками подобного рода (спам, флуд).
 
На текущий день цены на рынке распознавания каптч начинаются от 1$ за 1000 штук и заканчиваются 10$ за 1000 шутк. При больший объемах получается очень неплохая экономия. 

У каптчи есть один существенный минус — это невозможность всегда верно ее распознать, даже используя живого человека. Минус этот из-за того, что есть символы, которые при определенном искривлении и наложении друг на друга иногда становятся похожими друг на друга, например I L. Если близко поднести их друг к другу (а можно и наложить с отсутпом пару пх), то распознать визуально такую защиту будет достаточно трудоемко, не говоря уже о автоматизированном средстве распознавания.

Конечно, полагаться на защиту сервиса от вышеперечисленных атак используя одну лишь каптчу глупо, каптча не в силах полностью остановить атакующего, однако она способна значительно снизить процент атак на сервис и отпугнуть недоброжелателей. К тому же, в случае взлома алгоритма, его всегда можно оперативно поменять.

Доля атак в интернете растет каждый день все больше и больше, алгоритмы совершенствуются, вместе с ними совершенствуется и способы их атаки. Таким образом я делаю вывод, что задача по распознаванию каптчи (аудита безопасности алгоритма генерации каптчи), на текущий момент очень даже актуальна.

**Comment by sdukshis** [comment]
Нужны ссылки, подтверждающие следующие тезисы:

- По состоянию на 2013 год, каждый день пользователями по всей планете вводится примерно 320 миллионов каптчей.

- На текущий день цены на рынке распознавания каптч начинаются от 1$ за 1000 штук и заканчиваются 10$ за 1000 шутк. 

Стоит лучше позиционировать, что Вы выступаете на стороне аудитора, а не на стороне взломщика. Сейчас из текста это однозначно не следует.

В начале следует уделить немного расшифровке терминов. Следует пояснить само понятие и саму задачу.

Мне очень понравилась фраза "однако она способна значительно снизить процент атак". Из нее можно вывести, что в качестве формальных требований к задаче аудита может быть выдвинуто конкретное число - доля, которую можно распознать алгоритмами. Я думаю, что эту идею стоит развить в тексте.

**Comment by foma99999** [comment]
520 слов. Постарался учесть все неточности и рекомендации.
<hr>
На сегодняшний момент задача распознавания каптчи является актуальной, поскольку решив ее, можно произвести аудит безопасности алгоритма генерации каптчи.
Каптча — компьютерный тест, используемый для того, чтобы определить, кем является пользователь системы: человеком или компьютером.
Генерация — процесс создания каптчи.
Спам — Ненужные адресату электронные послания, рекламные письма и т. п., рассылаемые отдельными фирмами по Интернету или электронной почте.

Флуд — Ненужные адресату электронные послания, зачастую занимающие большие объёмы.

Распознавание каптчи — процесс представления символов каптчи в компьютере  (например, в текстовом редакторе).

Зачем это нужно? Все популярные сервисы, которыми пользуются миллионы людей, используют в качестве защиты от автоматизации действий каптчу. Распознавая графическую защиту мы может автоматизировать любое действие на данном сервисе: будь то рассылка спама, засорение базы данных миллионами «мусорных» регистрации или забивание тикет-системы техподдержки этими же миллионами «мусорных» запросов, тем самым, нанося убыток сервису и делая его менее комфортным для простых пользователей.
Проведя аудит, мы может сказать насколько сервис уязвим подобному способу атаки и при необходимости рассказать как можно максимально обезопасить сервис, делая каптчу максимально непригодной для автоматизированного распознавания, но возможной для распознавания человеком.
По состоянию на 2013 год, каждый день пользователями по всей планете вводится примерно 320 миллионов каптчей. [1]
Если приложить задачу немного в другое русло, то алгоритмы для распознавания каптчи можно использовать в качестве основы атакующего комплекса, что позволит сохранить огромные средства людям, занимающимся атаками подобного рода (спам, флуд), однако это русло является негативным и его мы рассматривать не будем.
На текущий день цены на рынке распознавания каптч начинаются от 0.7$ за 1000 штук и заканчиваются 10$ за 1000 шутк. [2] При больший объемах получается очень неплохая экономия.
У каптчи есть один существенный минус — это невозможность всегда верно ее распознать, даже используя живого человека. Минус этот из-за того, что есть символы, которые при определенном искривлении и наложении друг на друга иногда становятся похожими друг на друга, например I L. Если близко поднести их друг к другу (а можно и наложить с отсутпом пару пх), то распознать визуально такую защиту будет достаточно трудоемко, не говоря уже о автоматизированном средстве распознавания.
Конечно, полагаться на защиту сервиса от вышеперечисленных атак используя одну лишь каптчу глупо, каптча не в силах полностью остановить атакующего, однако она способна значительно снизить процент атак на сервис и отпугнуть недоброжелателей. Например, если алгоритм, пытающийся «обойти» защиту распознает 90% выборки, то такой алгорим является далек от идеала и использовать его для защиты не стоит. Идеальный алгоритм генерации каптчи  должен выдавать такие изображения, чтобы атакующий алгоримт расшифровывал их с точностью 0%. Однако ничего идеального нет, да и эти 0% — это лишь цифра, свидетельствующая о неточности атакующего алгоритма.  По моему мнению, оптимальной защитой будет если человек будет вводить 90% выборки верно, а атакующий алгоритм 20% верно.
Усложнив алгоритм до 0% ввода автоматизировано, мы скорее всего добьемся того, что человек будет вводить защиту с огромной ошибкой (из-за сложности визуального чтения).
В прочем, в случае взлома алгоритма, его всегда можно оперативно поменять или усложнить.
Доля атак в интернете растет каждый день все больше и больше, алгоритмы совершенствуются, вместе с ними совершенствуется и способы их атаки. Таким образом я делаю вывод, что задача по распознаванию каптчи (аудита безопасности алгоритма генерации каптчи), на текущий момент очень даже актуальна.
[1] - https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BF%D1%87%D0%B0
[2] – сервис по ручному вводу каптч http://antigate.com/

**Comment by sdukshis** [comment]
Лушче. Оформите как текстовый файл в репозитории. Потом это пойдет в текст диплома.
