### ISSUE TITLE
Записаться в школу по Глубинному обучению

### ISSUE THREAD

**Issue by sdukshis** [foma99999/diplom#21]
http://deepbayes.ru/#subscribe

Важная информация: прием заявок заканчивается 31 марта

**Comment by sdukshis** [comment]
@foma99999 если вы не успели зарегистрироваться, то просто закройте эту задачу.

**Comment by foma99999** [comment]
Я успел, однако решить задачку, которую давали в кач-ве задания, не смог.

**Comment by sdukshis** [comment]
ТАм сейчас проведут конкурс. Поскольку получилось больше 2-х человек на место. Посмотрим на результат.
