### ISSUE TITLE
Раздобыть Марк Лутц. Программирование на Python

### ISSUE THREAD

**Issue by sdukshis** [foma99999/diplom#5]
Поскольку основными языками программирования в области анализа данных являются R и Python, то для решения соответствующих задач нужно будет с ними ознакомиться.

В качестве основного языка будем использовать Python. Для его изучения потребуется литература https://www.litres.ru/mark-lutc/programmirovanie-na-python-tom-1-15232504/

**Comment by sdukshis** [comment]
Туда же добавлю следующие учебники:

   * М. Лутц "Изучаем Python", 4-е издание - [описание](https://www.ozon.ru/context/detail/id/32465307/)
   * A Byte of Python - можно легко найти в сети неофициальный перевод.

**Comment by foma99999** [comment]
С питоном сложностей возникнуть конечно не должно, к тому же будет огромным плюсом более детальное изучения языка, однако почему вы против использования того же php?
Ведь данная задача реализуема на этом языке. 
Я за питон, однако интересует Ваше мнение.

**Comment by sdukshis** [comment]
Главное преимущество Python для задач машинного обучения - это наличие большого числа готовых библиотек. 

Например, задача распознавания текста с картинки на данный момент очень успешно решается с помощью применения нейронных сетей. Конкретно сверхточных сетей. 

На этот счёт для языка python можно найти сразу несколько хороших библиотек. Например я в своей работе использую keras. 

Для других языков трудно найти тако разнообразие удобных инструментов. 

Я согласен, что на PHP можно самостоятельно реализовать готовый алгоритм, но чтобы сравнивать его с другими подходами удобней в качестве общего языка реализации использовать Python.
