### ISSUE TITLE
Зарегистрироваться на https://www.kaggle.com

### ISSUE THREAD

**Issue by sdukshis** [foma99999/diplom#6]
Для получения навыков решения задач машинного обучения очень удобно практиковаться на конкурсах.

Много конкурсов проходят на платформе https://www.kaggle.com

Необходимо создать там учетную запись

**Comment by sdukshis** [comment]
@foma99999 добавьте ссылку на учетную запись

**Comment by foma99999** [comment]
https://www.kaggle.com/foma9999
